# Generated by Django 4.0.3 on 2022-04-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='zipcode',
            new_name='Postcode',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='locality',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='customer',
            name='address2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
