# Generated by Django 4.0.3 on 2022-04-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_alter_orderplaced_status_verifiedemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=90)),
                ('user_email', models.EmailField(max_length=254)),
                ('report_message', models.CharField(default='', max_length=6000)),
            ],
        ),
    ]
