# Generated by Django 4.0.3 on 2022-04-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_productreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreport',
            name='select_report',
            field=models.CharField(choices=[('P', 'Product'), ('S', 'Shipping'), ('O', 'Order')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
