# Generated by Django 4.0.3 on 2022-04-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_productreport_select_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreport',
            name='select_report',
            field=models.CharField(choices=[('P', 'Product'), ('S', 'Shipping'), ('O', 'Order')], max_length=2, verbose_name='report'),
        ),
    ]
